language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
python:
  - '3.4'
  - '3.5'
  - '3.6'

# safelist branch to build
branches:
  only:
      - master

install:
  - python setup.py develop
  - pip install -r requirements-dev.txt

script:
  - mamba

notifications:
  email:
    - bifer@alea-soluciones.com
